name: Windows - Enhanced RustDesk

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: windows-latest
    timeout-minutes: 9999
    
    steps:
      - name: Downloading Essentials
        run: |
          Write-Host "Downloading essentials..."
          Invoke-WebRequest -Uri "https://gitlab.com/chamod12/win10-github-rdp-rustdesk/-/raw/main/Downloads.bat" -OutFile "C:\temp\Downloads.bat"
          Write-Host "Downloads.bat downloaded."
          
      - name: Install Essentials
        run: |
          Write-Host "Installing essentials..."
          cmd /c C:\temp\Downloads.bat
          Write-Host "Installation completed."

      - name: Log In To RustDesk
        run: |
          Write-Host "Logging in to RustDesk..."
          Invoke-WebRequest -Uri "https://gitlab.com/chamod12/win10-github-rdp-rustdesk/-/raw/main/show.bat" -OutFile "C:\temp\show.bat"
          cmd /c C:\temp\show.bat
          Write-Host "Logged in to RustDesk."

      - name: Time Counter
        run: |
          Write-Host "Running time counter..."
          Invoke-WebRequest -Uri "https://gitlab.com/chamod12/win10-github-rdp-rustdesk/-/raw/main/time.py" -OutFile "C:\temp\time.py"
          python C:\temp\time.py
          Write-Host "Time counter completed."
