name: Windows - RustDesk

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: windows-latest
    timeout-minutes: 9999
    
    steps:
      - name: Downloading & Installing Essentials
        run: |
          Invoke-WebRequest -Uri "https://gitlab.com/chamod12/win10-github-rdp-rustdesk/-/raw/main/Downloads.bat" -OutFile "C:\temp\Downloads.bat"
          Invoke-WebRequest -Uri "https://gitlab.com/chamod12/win10-github-rdp-rustdesk/-/raw/main/show.bat" -OutFile "C:\temp\show.bat"
          Invoke-WebRequest -Uri "https://gitlab.com/chamod12/win10-github-rdp-rustdesk/-/raw/main/time.py" -OutFile "C:\temp\time.py"
          cmd /c C:\temp\Downloads.bat

      - name: Log In To RustDesk
        run: cmd /c C:\temp\show.bat

      - name: Time Counter
        run: python C:\temp\time.py
